import { Inter } from 'next/font/google'
import './globals.css'
import { TransactionProvider } from '@/context/TransactionContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'ChainPay',
  description: 'Generated by create next app',
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png'],
  }
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><TransactionProvider>{children}</TransactionProvider></body>
    </html>
  )
}
